### ISSUE TITLE
Mail sending fails with WBCE 1.2-alpha4

### ISSUE THREAD

**Issue by instantflorian** [WBCE/form#1]
error message:
Fatal error: Uncaught Error: 
Call to a member function get_email() on null in /.../modules/form/view.php:44 
Stack trace: 
#0 /.../modules/form/view.php(296): emailAdmin() 
#1 /.../framework/frontend.functions.php(246): require('/var/www/wxxx...') 
#2 /.../templates/wbce/index.php(83): page_content(1) 
#3 /.../index.php(82): require('/var/www/wxxx...') 
#4 /.../pages/frmlr.php(8): require('/var/www/wxxx...') #5 {main} 
thrown in /.../modules/form/view.php on line 44

**Comment by instantflorian** [comment]
Forget it, can't reproduce the error

**Comment by NorHei** [comment]
can we close this ??

**Comment by NorHei** [comment]
oh sorry .. already closed ...
